server:
  port: 8087

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/sns
    username: ${name}
    password: ${pw}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
      dialect: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate.format_sql: true
    show-sql: true
  redis:
    url: redis://localhost:6379
    host: localhost
    port: 6379


jwt:
  secret-key: fast-campus.simple_sns_2022_secret_key
  # 30 days
  token.expired-time-ms: 2592000000

spring.kafka:
    properties:
      security.protocol: PLAINTEXT  # ?? ???? ??
    consumer:
      properties.spring.json.trusted.packages: "*"  # JSON ??? ?? ??
      bootstrap-servers: localhost:9092  # ?? Kafka ??? ??
      group-id: notification  # ??? ?? ID
      auto-offset-reset: latest  # ?? ????? ??
      key-deserializer: org.apache.kafka.common.serialization.IntegerDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
    listener:
      ack-mode: MANUAL  # ?? ACK ??
    producer:
      bootstrap-servers: localhost:9092  # ?? Kafka ??? ??
      key-serializer: org.apache.kafka.common.serialization.IntegerSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties.enable.idempotence: false  # ??? ????
    topic:
      notification: notification-topic  # ???? ??? ?? ??


#spring:
#  kafka:
#    properties:
#      security.protocol: SASL_SSL
#      sasl.mechanism: SCRAM-SHA-256
#      sasl.jaas.config: org.apache.kafka.common.security.scram.ScramLoginModule required username="r2rj2fh0" password="e_BnIr6ESAbpmuu7L7XugsMNmYlx3eFq";
#    consumer:
#      properties.spring.json.trusted.packages: "*"
#      bootstrap-servers: dory-01.srvs.cloudkafka.com:9094, dory-02.srvs.cloudkafka.com:9094, dory-03.srvs.cloudkafka.com:9094
#      group-id: notification
#      auto-offset-reset: latest
#      key-deserializer: org.apache.kafka.common.serialization.IntegerDeserializer
#      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
#    listener:
#      ack-mode: MANUAL
#    producer:
#      bootstrap-servers: dory-01.srvs.cloudkafka.com:9094, dory-02.srvs.cloudkafka.com:9094, dory-03.srvs.cloudkafka.com:9094
#      key-serializer: org.apache.kafka.common.serialization.IntegerSerializer
#      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
#      properties.enable.idempotence: false
#    topic:
#      notification: r2rj2fh0-notification
